### ISSUE TITLE
Error when saving extension and no dk working

### ISSUE THREAD

**Issue by patrick-mota** [brpaz/ulauncher-docker#1]
First of all thank you for your extension :+1: 

I have a problem when I try to add your extension, I got an error and even if I click save and go back to the launcher I still can use "dk".

I have installed python + the extension you said in your readme and still having the same message.

"Unexpected API error. KeyError: com.github.brpaz.ulauncher-docker"

Some information about my configuration:

OS: Ubuntu 18.10
Last ulauncher version
pip version 9.0.1 and python 2.7
Docker: CE 18.09

**Comment by brpaz** [comment]
That error message usually means some missing python package.

Please stop ulauncher and run from the command line:` ulauncher -v` and paste the output here, so I can look at it in more detail.

**Comment by patrick-mota** [comment]
@brpaz Sorry didn't saw your reply ! Thank you

I did ulauncher -v and I think the revelant part is : 
`2019-02-20 08:43:50,259 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-docker" exited instantly with code 1
/usr/lib/python2.7/dist-packages/ulauncher/util/image_loader.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
`

Here is the full log if you need it : 

`ulauncher -v
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
2019-02-20 08:43:50,031 | INFO | ulauncher: main() | Ulauncher version 4.3.1.r4
2019-02-20 08:43:50,031 | INFO | ulauncher: main() | GTK+ 3.24.1
2019-02-20 08:43:50,032 | INFO | ulauncher: main() | Is Wayland: False
2019-02-20 08:43:50,032 | INFO | ulauncher: main() | Wayland compatibility: off
2019-02-20 08:43:50,061 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2019-02-20 08:43:50,065 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2019-02-20 08:43:50,065 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2019-02-20 08:43:50,065 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2019-02-20 08:43:50,066 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2019-02-20 08:43:50,067 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2019-02-20 08:43:50,067 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2019-02-20 08:43:50,067 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2019-02-20 08:43:50,067 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2019-02-20 08:43:50,067 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2019-02-20 08:43:50,068 | DEBUG | ulauncher.util.display: get_screens() | Found 3 monitor(s).
2019-02-20 08:43:50,068 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2019-02-20 08:43:50,069 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 1 - X: 1920, Y: 0, W: 1920, H: 1080
2019-02-20 08:43:50,069 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 2 - X: 3840, Y: 0, W: 1920, H: 1080
2019-02-20 08:43:50,071 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2019-02-20 08:43:50,074 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2019-02-20 08:43:50,074 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2019-02-20 08:43:50,088 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.pywkm.ulauncher-spotify" started. PID 6279
2019-02-20 08:43:50,093 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.noam09.ulauncher-remmina" started. PID 6281
2019-02-20 08:43:50,123 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-docker" started. PID 6284
2019-02-20 08:43:50,155 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary><Alt>space
Traceback (most recent call last):
  File "/home/ganon/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-docker/main.py", line 8, in <module>
    import docker
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/home/ganon/.local/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
2019-02-20 08:43:50,259 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.brpaz.ulauncher-docker" exited instantly with code 1
/usr/lib/python2.7/dist-packages/ulauncher/util/image_loader.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio, GLib, GdkPixbuf
/usr/lib/python2.7/dist-packages/ulauncher/util/image_loader.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio, GLib, GdkPixbuf
2019-02-20 08:43:50,324 | INFO | ulauncher.util.desktop.reader: find_apps_cached() | Found 80 apps in cache
2019-02-20 08:43:50,336 | INFO | ulauncher.util.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/vim.desktop": constructor returned NULL
2019-02-20 08:43:50,358 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.pywkm.ulauncher-spotify" connected
2019-02-20 08:43:50,359 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.pywkm.ulauncher-spotify"
com.github.pywkm.ulauncher-spotify | 2019-02-20 08:43:50,361 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2019-02-20 08:43:50,366 | INFO | ulauncher.util.desktop.reader: find_apps_cached() | Found 80 apps in the system
2019-02-20 08:43:50,367 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.29 seconds
2019-02-20 08:43:50,378 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2019-02-20 08:43:50,389 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.noam09.ulauncher-remmina" connected
2019-02-20 08:43:50,390 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.noam09.ulauncher-remmina"
DEBUG:ulauncher.api.client.Client:Incoming event PreferencesEvent
com.github.noam09.ulauncher-remmina | 2019-02-20 08:43:50,391 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
`


and If I go in Settings and click in "Save" I got this message in logs:
`2019-02-20 08:50:56,262 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_update_prefs() | Update extension preferences: {'callback': '__jp4', 'pref.item_name': 'Item', 'id': 'com.github.brpaz.ulauncher-docker', 'pref.kw': 'dk'}
2019-02-20 08:50:56,262 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: com.github.brpaz.ulauncher-docker
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-docker'
`

**Comment by brpaz** [comment]
Ok. Here what is causing the error: "ImportError: No module named ssl_match_hostname"

It seems an issue of the docker-py module.. See https://github.com/docker/docker-py/issues/1502. There are some potential solutions in that thread. Can you have a look?

**Comment by patrick-mota** [comment]
Thank you.

I did the following:
`sudo cp -r ~/.local/lib/python2.7/site-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports`

and

`sudo apt install python-docker`

Now I can click "Save" without any error but still not working.

I suspect he try to get my docker config from a wrong path:

`com.github.brpaz.ulauncher-docker | 2019-02-22 14:15:06,762 | DEBUG | docker.utils.config: find_config_file() | Trying paths: ['/home/ganon/.docker/config.json', '/home/ganon/.dockercfg']
com.github.brpaz.ulauncher-docker | 2019-02-22 14:15:06,762 | DEBUG | docker.utils.config: find_config_file() | No config file found
com.github.brpaz.ulauncher-docker | 2019-02-22 14:15:06,762 | DEBUG | docker.utils.config: find_config_file() | Trying paths: ['/home/ganon/.docker/config.json', '/home/ganon/.dockercfg']
com.github.brpaz.ulauncher-docker | 2019-02-22 14:15:06,763 | DEBUG | docker.utils.config: find_config_file() | No config file found
2019-02-22 14:15:06,765 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.brpaz.ulauncher-docker" connected
2019-02-22 14:15:06,766 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.brpaz.ulauncher-docker"
com.github.brpaz.ulauncher-docker | 2019-02-22 14:15:06,768 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
^CERROR:ulauncher.api.client.Client:WS Client error 
com.github.brpaz.ulauncher-docker | 2019-02-22 14:16:34,775 | ERROR | ulauncher.api.client.Client: on_error() | WS Client error 
2019-02-22 14:16:34,777 | INFO | ulauncher.api.server.ExtensionController: handleClose() | Extension "com.github.brpaz.ulauncher-docker" disconnected
com.github.brpaz.ulauncher-docker | 2019-02-22 14:16:34,777 | WARNING | ulauncher.api.client.Client: on_close() | Connection closed. Exiting
com.github.brpaz.ulauncher-docker | 2019-02-22 14:16:34,778 | DEBUG | ulauncher.api.client.Extension: trigger_event() | No listeners for event SystemExitEvent
`

**Comment by patrick-mota** [comment]
You can close this issue I think :) it's more related to docker-py than your plugin I guess.
Thank for your help
